name: Advanced CI Pipeline

on:
  # Disabled to speed up CI - only run on manual trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8  # Reasonable timeout
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with coverage (fast)
      run: |
        pytest -v --tb=short --cov=utils --cov=main --cov-report=xml -x
