name: Quick Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3  # Very fast timeout
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies (minimal)
      run: |
        pip install pytest pytest-asyncio
        pip install -r requirements.txt --no-deps  # Skip heavy dependencies
        
    - name: Run critical tests only
      run: |
        pytest tests/test_scraper.py -v --tb=short -x
